# Azure Pipelines for Node.js (lightweight version)
trigger:
- master

pool:
  name: Default  

steps:
- checkout: self
  fetchDepth: 1

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Cleaning npm cache..."
    npm cache clean --force
    rm -rf node_modules
  displayName: 'Clean cache and node_modules'

- script: |
    npm ci
  displayName: 'Install dependencies (lightweight)'

- script: |
    npm run build --if-present
  displayName: 'Build project (if build script exists)'
  continueOnError: true
